name: PR
on:
  pull_request:
    branches: [ master, main ]
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: VERSION
        run: mvn -version

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittests # optional
          name: coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
